### ISSUE TITLE
uncorrect frequency report in period and range file

### ISSUE THREAD

**Issue by oloapinivad** [IS-ENES-Data/QA-DKRZ#10]
I am running the qa-dkrz under conda and it works fine.

However, the .period and .range table reports a wrong "frequency"

```
--- # Time intervals of atomic variables.

- frequency: gr
  number_of_variables: 79
  - variable: rsdt_Amon_EC-Earth3_historical_r4i1p1f1_gr
    begin: 1850-01-01T00:00:00
    end: 1850-12-01T00:00:00
...

```
I suspect the problem is coming from `qa_summary.py ` in the `period_final` function, more or less here: the string splitting is not working in the supposed way I guess. 

```
...
 word = name.rsplit('_', 2)
            if len(word) > 2:
                for j in range(len(frqs)):
                    if word[2] == frqs[j]:
                        frqs_id[j].append(i)
                        break
                   else:
                    # append new lists
                    frqs.append(word[2])
                    frqs_id.append([i])
                    frqs_beg.append(self.atomicBeg[i])
                    frqs_end.append(self.atomicEnd[i])

...
```

**Comment by uwefladrich** [comment]
I can confirm the problem.

A long shot, but in case it is *not* just the summary presentation: Could it have to do with the definition of the file name encoding for CMIP6? I noted that it says (`CMIP6/CMIP6_DRS_CV.csv`):
```
CMIP6-FE:<variable_id>/<table_id>/<source_id>/<experiment_id>/<member_id>\
           /<grid_label>.nc
```
i.e. without any mentioning of the temporal subset. In contrast, the CMIP5 definition is
```
CMIP5-FE:<variable name>_<MIP table>_<model>_<experiment>_<ensemble member>\
           _<temporal subset>_<geographical info>.nc
```
But I'm not excluding that @oloapinivad is correct with the suggestion above.

**Comment by h-dh** [comment]
Thanks a lot for the bug report.
a) the missing temporal subset in file CMIP6_DRS_CV.csv is intentionially. This is managed in the program elsewhere.
b) there was in deed a bug with the periods. The state of the program degraded somehow with the result that writing the period to the log-files got lost. (I didn't realised this in my operational work, because I'm using a different approach). The bug is fixed together with another one concerning fx files. I scheduled a maintenance for a general check of the python program, so there is no update, yet.

**Comment by uwefladrich** [comment]
> Thanks a lot for the bug report.
> a) the missing temporal subset in file CMIP6_DRS_CV.csv is intentionially. This is managed in the program elsewhere.

Okay. I was confused because it's present for CMIP5, but not CMIP6.

> b) there was in deed a bug with the periods. The state of the program degraded somehow with the result that writing the period to the log-files got lost. (I didn't realised this in my operational work, because I'm using a different approach). The bug is fixed together with another one concerning fx files. I scheduled a maintenance for a general check of the python program, so there is no update, yet.

For us it's most important to know if it is a diag problem in qa-dkrz or something wrong in our data. Good to hear you're planning to work on it. Appreciated!

**Comment by h-dh** [comment]
fixed.
Reason of the bug: the last major coding of the code was based on CORDEX, which has frequency in the filename. But, CMIP5/6 don't have this. Instead the table_id is given at a different position in the filename.

PLease, note that the bug affected only the human readable table with the extension '.range', which gives a hint whether the sub-temporal files of all varaibles associated to a given freq./table_id span identical ranges.

conda poackage is pending.
cheers,
hdh
