### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by stephank16** [IS-ENES-Data/QA-DKRZ#6]
a simple and documented way to get the version info of qa-dkrz would be helpfull

e.g. qa-dkrz -v
-- output of prepare version integrated
-- output of cv version used
-- output of qa-dkrz tool version (e.g. git tag etc.)
etc.

especially for support questions, such that we can ask for "please run qa-dkrz -v and send output to us etc."

**Comment by h-dh** [comment]
-- output of PrePARE version integrated:
    PrePARE is not integrated, but downloaded by conda at first run-time, thus the tag would be that of the corresponding package. It appears to me that PrePARE uses a special set of tables derived from  https://github.com/WCRP-CMIP/CMIP6_CVs. It is not clear to me, whether a specific conda package is independent on the version of the tables. Thus, the two are only updated by qa-dkrz together, if updating is triggered.

I think any question about PrePARE related issues should be forwarded to D. Nadeau, the developer of PrePARE.

-- output of cv version used:
  QA-DKRZ is not used only for CMIP6, but for other projects, too, having perhaps no precise tagging of the CV (e.g. CORDEX with its Archive Design stuck to Version 3.1 modified several times).
Thus, the outcome depends on the project.

There are now two new options (-v, --version), which will be effective for the master branch after a next push for qa-dkrz. 

However for support questions, it would be more helpful, if users would provide the output of

   qa-dkrz --debug users-command-line &> output-file  # syntax for redirection when bash is used

Cheers, 
hdh
