### ISSUE TITLE
Installation issues via git.

### ISSUE THREAD

**Issue by BertvanUlft** [IS-ENES-Data/QA-DKRZ#7]
Hi,

while setting up a fresh QA-DKRZ installation via the git-route (as opposed to conda) I ran into a few minor issues.

- compilation error:
install gave following error:
```
In file included from /nobackup/users/ulft/programs/QC/QA-DKRZ/src/getNC_att.cpp:17:0:
/nobackup/users/ulft/programs/QC/QA-DKRZ/src/NcAPI.cpp: In member function ‘void NcAPI::layoutVarDataPushesStr(MtrxArr<char*>&, std::__cxx11::string&)’:
/nobackup/users/ulft/programs/QC/QA-DKRZ/src/NcAPI.cpp:4429:11: error: invalid conversion from ‘char’ to ‘char*’ [-fpermissive]
   char* p='';
           ^~~~
make: *** [/nobackup/users/ulft/programs/QC/QA-DKRZ/Makefile:50: getNC_att.x] Error 1
```

Changed line 4429 to:
`   char* p=(char*)'\n';`

- link to lib incorrect:
in install_configure LIB is set to /usr/lib64. Install then complains:
`ln: failed to create symbolic link '/nobackup/users/ulft/programs/QC/QA-DKRZ/local/lib64': Permission denied
```
ll /nobackup/users/ulft/programs/QC/QA-DKRZ/local
lrwxrwxrwx 1 ulft afd_rdwk 10 Apr 25 16:45 /nobackup/users/ulft/programs/QC/QA-DKRZ/local -> /usr/lib64/
```
Solved this by changing the link to:
```
ll /nobackup/users/ulft/programs/QC/QA-DKRZ/local
total 0
lrwxrwxrwx 1 ulft afd_rdwk 10 Apr 25 16:48 lib64 -> /usr/lib64/
```

- standard-names.html retrieval
The table QA_Tables/tables/projects/CF/standard-names.html is somehow retrieved as a binary file.
Solved this by downloading the file manually:
curl http://cfconventions.org/standard-names.html > QA_Tables/tables/projects/CF/standard-names.html

- CF_area-type-table.txt and CF_standardized-region-names.txt missing
These tables are not available in the QA_TABLES directory. Copied them from an old installation for now as a temporary fix.

best wishes,

Bert van Ulft (KNMI)

**Comment by h-dh** [comment]
Hi,

I am rather amazed by your issue note:

-  looking to line 4429 of NcAPI.cpp there is
   char* p='\0'; which was compiled fine (with -Wall)
- a fresh installation would not download or create any directory 'local' as it was done in the past.
-  QA_Tables/tables/projects/CF/standard-names.html is downloaded and used as XML original from
   cfconventions.org

Perhaps, you're stuck to an older version, which might have been modified?
Did you do
git clone https://github.com/IS-ENES-Data/QA-DKRZ and run './install PROJECT'?

'git log' reveiled as last info:
commit 01daa50cd24941324ec9d3e22f391adf93b0be28 (HEAD -> master, origin/master, origin/HEAD)
Author: Heinz-Dieter Hollweg <hollweg.dkrz.de>
Date:   Mon Apr 23 18:01:42 2018 +0200

    failed glibc

This was something to solve an issue with our HPC at DKRZ.

Cheers,
hdh

**Comment by BertvanUlft** [comment]
Hi Heinz-Dieter,

we hadn't updated QA for a long time, but now we need to start using it again so that's why I decided to do a completely fresh install.
I removed the QA-DKRZ and ~/.qa-dkrz directories, then cloned the repository and finally './install CORDEX'. Steps to reproduce:

```
rm -rf QA-DKRZ ~/.qa-dkrz
git clone https://github.com/IS-ENES-Data/QA-DKRZ
cd QA-DKRZ
cp ../install_configure .
./install CORDEX
  Please, specify variable QA_TABLES [default: /nobackup/users/ulft/programs/QC/QA-DKRZ/QA_Tables], 
the spot for external tables and programs: [pressed enter]
```
This gives:
`grep failed to find string Standard Name Table in file standard-names.html`
and QA_Tables/tables/projects/CF/standard-names.html is an human-unreadable binary file.

Then retrieved this file manually:
`curl http://cfconventions.org/standard-names.html > QA_Tables/tables/projects/CF/standard-names.html`

and then rerun install, which gives:
```
./install CORDEX
make: Entering directory '/nobackup/users/ulft/programs/QC/QA-DKRZ/bin'
/usr/bin/gcc -Wall -DSTATVFS -o diskUsage.x /nobackup/users/ulft/programs/QC/QA-DKRZ/src/diskUsage.c
/usr/bin/gcc -Wall -DSTATVFS -o fModTime.x /nobackup/users/ulft/programs/QC/QA-DKRZ/src/fModTime.c
/usr/bin/gcc -Wall -DSTATVFS -o unixTime.x /nobackup/users/ulft/programs/QC/QA-DKRZ/src/unixTime.c
/usr/bin/g++ -Wall -std=c++11 -D NC4 -o check_CORDEX_standard-table.x  /nobackup/users/ulft/programs/QC/QA-DKRZ/src/check_CORDEX_standard-table.cpp \
        -I /nobackup/users/ulft/programs/QC/QA-DKRZ/include -I/usr/include -I/usr/include/udunits2 -L/usr/lib64  -ludunits2 -lnetcdf -lhdf5_hl -lhdf5 -lz -luuid 
/usr/bin/g++ -Wall -std=c++11 -D NC4 -o convert_CF-standard-names.x  /nobackup/users/ulft/programs/QC/QA-DKRZ/src/convert_CF-standard-names.cpp \
        -I /nobackup/users/ulft/programs/QC/QA-DKRZ/include -I/usr/include -I/usr/include/udunits2 -L/usr/lib64  -ludunits2 -lnetcdf -lhdf5_hl -lhdf5 -lz -luuid 
/usr/bin/g++ -Wall -std=c++11 -D NC4 -o getNC_att.x  /nobackup/users/ulft/programs/QC/QA-DKRZ/src/getNC_att.cpp \
        -I /nobackup/users/ulft/programs/QC/QA-DKRZ/include -I/usr/include -I/usr/include/udunits2 -L/usr/lib64  -ludunits2 -lnetcdf -lhdf5_hl -lhdf5 -lz -luuid 
In file included from /nobackup/users/ulft/programs/QC/QA-DKRZ/src/getNC_att.cpp:17:0:
/nobackup/users/ulft/programs/QC/QA-DKRZ/src/NcAPI.cpp: In member function ‘void NcAPI::layoutVarDataPushesStr(MtrxArr<char*>&, std::__cxx11::string&)’:
/nobackup/users/ulft/programs/QC/QA-DKRZ/src/NcAPI.cpp:4429:11: error: invalid conversion from ‘char’ to ‘char*’ [-fpermissive]
   char* p='';
           ^~~~
make: *** [/nobackup/users/ulft/programs/QC/QA-DKRZ/Makefile:50: getNC_att.x] Error 1
make: Leaving directory '/nobackup/users/ulft/programs/QC/QA-DKRZ/bin'
```

install_configure contains:
```
# ============ Please, edit setting =========
# ============ Assignment containing spaces must be surrounded by "

# C compiler
CC="/usr/bin/gcc"

# C++ compiler
CXX="/usr/bin/g++"

# C compiler options
CFLAGS="-Wall"

# C++ compiler options
CXXFLAGS="-Wall -std=c++11 -D NC4"

# Path to libraries (netcdf4 and related, uuid, udunits).
# Prefix of '-L' may be skipped.
# e.g. LIB=/path/local/lib:/path/local/lib64
LIB=/usr/lib64

# Path to header files (netcdf4 and related, uuid, udunits).
# Prefix of '-I' may be skipped.
# e.g. INCLUDE=/path/local/include
INCLUDE=/usr/include:/usr/include/udunits2
```

I came across a page, which seems to describe the issue: https://stackoverflow.com/questions/20944784/why-is-conversion-from-string-constant-to-char-valid-in-c-but-invalid-in-c#20944858

best wishes,

Bert

**Comment by BertvanUlft** [comment]
The "char* p='\0'" has been fixed in the latest version.
Some of the tables were downloaded by wget using compression, so the files were gzipped. This can be fixed by adding '--compression=auto' to the wget commands in scripts/get_externalSources.
